# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u5217\u8868',
                'verbose_name_plural': '\u6587\u7ae0\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300, verbose_name='\u6587\u7ae0\u7b80\u4ecb')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('author', models.CharField(max_length=10, verbose_name='\u4f5c\u8005')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
                ('comment', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('body', models.TextField(verbose_name='\u6b63\u6587')),
                ('image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='illustration/%Y/%m', verbose_name='\u63d2\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u4fe1\u606f',
                'verbose_name_plural': '\u6587\u7ae0\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='\u6807\u7b7e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Label', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Articles', verbose_name='\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Label', verbose_name='\u6807\u7b7e'),
        ),
    ]
