# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 18:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9\t'),
        ),
    ]
