# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180207_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='label1',
        ),
        migrations.AddField(
            model_name='label',
            name='label2',
            field=models.CharField(default='', max_length=10, verbose_name='\u6807\u7b7e'),
        ),
    ]
