# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180208_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=10, verbose_name='\u6807\u7b7e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Label_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=10, verbose_name='\u6807\u7b7e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.RemoveField(
            model_name='articlelist',
            name='label',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='label',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='articlelist',
            name='label_one',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Label_One', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='label_two',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Label_Two', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='articles',
            name='label_one',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Label_One', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='articles',
            name='label_two',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Label_Two', verbose_name='\u6807\u7b7e'),
        ),
    ]
