# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 14:15
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='top',
            name='body',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6b63\u6587'),
        ),
    ]
