# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180208_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='top',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
