# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 15:23
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180208_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grow_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('body', DjangoUeditor.models.UEditorField(default='', verbose_name='\u6b63\u6587')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6210\u957f\u7ecf\u5386',
                'verbose_name_plural': '\u6210\u957f\u7ecf\u5386',
            },
        ),
    ]
