# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_grow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grow_up',
            name='body',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
    ]
