# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180208_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('body', models.TextField(verbose_name='\u6b63\u6587')),
                ('image', models.ImageField(max_length=200, upload_to='talk/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bf4\u8bf4',
                'verbose_name_plural': '\u8bf4\u8bf4',
            },
        ),
    ]
