# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_talk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Label_One',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='articlelist',
            old_name='label_one',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='articlelist',
            name='label_two',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='label_two',
        ),
        migrations.DeleteModel(
            name='Label_Two',
        ),
    ]
