# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 11:48
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20180209_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300, verbose_name='\u6587\u7ae0\u7b80\u4ecb')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('author', models.CharField(max_length=10, verbose_name='\u4f5c\u8005')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
                ('comment', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('body', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9\t')),
                ('image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='illustration/%Y/%m', verbose_name='\u63d2\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7b14\u8bb0\u4fe1\u606f',
                'verbose_name_plural': '\u7b14\u8bb0\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Study_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='\u7b14\u8bb0\u6807\u7b7e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='StudyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Study', verbose_name='\u7b14\u8bb0\u4fe1\u606f')),
                ('study_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Study_label', verbose_name='\u5b66\u4e60\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u5217\u8868',
                'verbose_name_plural': '\u6587\u7ae0\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='study_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Study_label', verbose_name='\u5b66\u4e60\u6807\u7b7e'),
        ),
    ]
