# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20180209_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8d44\u6e90\u540d')),
                ('image', models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('url', models.URLField(verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d44\u6e90\u5217\u8868',
                'verbose_name_plural': '\u8d44\u6e90\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='study_label',
            options={'verbose_name': '\u7b14\u8bb0\u6807\u7b7e', 'verbose_name_plural': '\u7b14\u8bb0\u6807\u7b7e'},
        ),
        migrations.AlterModelOptions(
            name='studylist',
            options={'verbose_name': '\u7b14\u8bb0\u5217\u8868', 'verbose_name_plural': '\u7b14\u8bb0\u5217\u8868'},
        ),
    ]
