# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20180228_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grow_up',
        ),
        migrations.AddField(
            model_name='resources',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='\u7b80\u4ecb'),
        ),
    ]
