# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20180228_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='url',
        ),
        migrations.AddField(
            model_name='resources',
            name='download',
            field=models.FileField(default='', max_length=200, upload_to='resources/%Y/%m', verbose_name='\u4e0b\u8f7d\u94fe\u63a5'),
        ),
    ]
