# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20180228_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='download_nums',
            field=models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6b21\u6570'),
        ),
    ]
