# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_resources_download_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='download_nums',
        ),
    ]
